[package]
name = "pairing-crypto-jni"
authors = ["MATTR Global Team"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
