/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pairing_crypto;

import org.junit.Test;
import static org.junit.Assert.*;

public class BbsTest {
       
    @Test public void shouldThrowExceptionMessageWhenFailToGenerateBbsBls12381KeyPair() {
        byte[] ikm = null;
        byte[] keyInfo = null;

        try {
            Bbs.generateBls12381KeyPair(ikm, keyInfo);
            fail("Expected an exception to be thrown");
        } catch (Exception exception) {
            assertEquals("Unable to generate keys", exception.getMessage());
        }
    }

    @Test public void canGenerateBbsBls12381KeyPair() {
        byte[] ikm = new byte[32];
        byte[] keyInfo = null;
        KeyPair keyPair = null;

        try {
            keyPair = Bbs.generateBls12381KeyPair(ikm, keyInfo);
        } catch (Exception exception) {
            exception.printStackTrace();
        }

        assertNotNull(keyPair);
        assertEquals(KeyPair.BBS_BLS12381_PUBLIC_KEY_SIZE, keyPair.publicKey.length);
        assertEquals(KeyPair.BBS_BLS12381_SECRET_KEY_SIZE, keyPair.secretKey.length);
    }

}
