name: ci-wrapper-rn

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test:
    name: Build & Test RN Wrapper
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wrappers/react-native
    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # pin@v3.5.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

  build_ios:
    name: Build iOS Library
    runs-on: macos-latest
    if: "github.ref == 'refs/heads/master'"
    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # pin@v3.5.1

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # pin@v1.0.6
        with:
          profile: minimal
          # TODO(DEBT): Remove usage of deprecated action and switch to the latest stable
          toolchain: 1.82.0
          override: true

      - name: Build Libraries for iOS
        working-directory: ./wrappers/react-native
        run: yarn build:ios

      - uses: actions/upload-artifact@v4
        with:
          name: ios-build-artifacts
          path: ./wrappers/react-native/ios/lib
          if-no-files-found: error
          retention-days: 1

  build_android:
    name: Build Android Library
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/master'"
    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # pin@v3.5.1

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # pin@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build Libraries for Android
        working-directory: ./wrappers/react-native
        run: yarn build:android

      - uses: actions/upload-artifact@v4
        with:
          name: android-build-artifacts
          path: ./wrappers/react-native/android/lib
          if-no-files-found: error
          retention-days: 1

  publish_unstable:
    name: Publish unstable package release
    runs-on: macos-latest
    needs: [build_test, build_ios, build_android]
    if: "github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, 'chore(release): publish')"
    defaults:
      run:
        working-directory: ./wrappers/react-native
    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # pin@v3.5.1

      - uses: actions/download-artifact@v5
        with:
          name: ios-build-artifacts
          path: ./wrappers/react-native/ios/lib

      - uses: actions/download-artifact@v5
        with:
          name: android-build-artifacts
          path: ./wrappers/react-native/android/lib

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org

      - name: Run yarn install
        run: yarn install --frozen-lockfile

      - name: Run yarn build
        run: yarn build

      - name: Configure NPM JS User
        run: |
          git config user.name "Mattr CI"
          git config user.email "npmjs_ci_mattr_public@mattr.global"
          npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}

      - name: Publish unstable build
        run: yarn publish:unstable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}

  publish_release:
    name: Publish package release
    runs-on: macos-latest
    needs: [build_test, build_ios, build_android]
    if: "github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, 'chore(release): publish')"
    defaults:
      run:
        working-directory: ./wrappers/react-native
    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # pin@v3.5.1

      - uses: actions/download-artifact@v5
        with:
          name: ios-build-artifacts
          path: ./wrappers/react-native/ios/lib

      - uses: actions/download-artifact@v5
        with:
          name: android-build-artifacts
          path: ./wrappers/react-native/android/lib

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org

      - name: Run yarn install
        run: yarn install --frozen-lockfile

      - name: Run yarn build
        run: yarn build

      - name: Configure NPM JS User
        run: |
          git config user.name "Mattr CI"
          git config user.email "npmjs_ci_mattr_public@mattr.global"
          npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}

      - name: Publish release build
        run: yarn publish:release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
