name: Mirror repository to mattrassurance org
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  MirrorRepoToMATTRAssurance:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: mirror repo
        shell: bash
        run: |
          rm -r .git
          rm -r .github
          git init --initial-branch=${{ env.GITHUB_REF_NAME }}
          git config --local user.name ${{ secrets.MATTRASSURANCE_GIT_USER_NAME }}
          git config --local user.email ${{ secrets.MATTRASSURANCE_GIT_USER_EMAIL }}
          git add .
          git commit -m "Backing up ${{ env.GITHUB_REPOSITORY }} to mattrassurance org"
          git remote add origin https://${{ secrets.MATTRASSURANCE_GIT_USER_NAME }}:${{ secrets.MATTRASSURANCE_GIT_USER_PAT }}@github.com/mattrassurance/pairing_crypto.git
          git push origin ${{ env.GITHUB_REF_NAME }} --force
