name: Mirror repository to S3
on:
  push:
    branches:
      - master
jobs:
  BackupRepoToS3:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # pin@v6.0.3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # pin@v6.2.0
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.gh_backup_role }}
          role-duration-seconds: 900
          role-session-name: GithubActions

      - name: Backing up this repo to AWS S3
        uses: peter-evans/s3-backup@4f39c7dab63c7666d6ba6722d7966e7d0655583c # pin @v1.1.0
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          MIRROR_TARGET: ${{ secrets.gh_backup_location }}/pairing_crypto
          SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
        with:
          args: --overwrite --remove
