name: Mirror repository to mattrassurance org
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  MirrorRepoToMATTRAssurance:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: mirror repo
        env:
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          GITHUB_REF_NAME: ${{ env.GITHUB_REF_NAME }}
          REMOTE_GIT_USER_NAME: ${{ secrets.MATTRASSURANCE_GIT_USER_NAME }}
          REMOTE_GIT_USER_EMAIL: ${{ secrets.MATTRASSURANCE_GIT_USER_EMAIL }}
          REMOTE_GIT_USER_PAT: ${{ secrets.MATTRASSURANCE_GIT_USER_PAT }}
        shell: bash
        run: |
          rm -r .git
          rm -r .github
          git init --initial-branch=${GITHUB_REF_NAME}
          git config --local user.name ${REMOTE_GIT_USER_NAME}
          git config --local user.email ${REMOTE_GIT_USER_EMAIL}
          git add .
          git commit -m "Backing up ${GITHUB_REPOSITORY} to mattrassurance org"
          git remote add origin https://${REMOTE_GIT_USER_NAME}:${REMOTE_GIT_USER_PAT}@github.com/mattrassurance/pairing_crypto.git
          git push origin ${GITHUB_REF_NAME} --force
